### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Legnatbird** [LUXTACO/DBFarmer#1]
OS: Windows 11
Python: 3.12.2
Emulator: Memu
Resolution: 1366*768 (os)

Runs fine but, the bot not detect any object to interact

**Comment by LUXTACO** [comment]
You might need to re take the screenshots, just go thru the game and take
screenshots of the elements and replace them, make sure your game is in
English and that you don't have something like HDR on! If the problem
persists change the confidence value inside the program
